import Config

shared_env = Path.expand("~/.config/eirinchan-shared.env")

read_shared_env = fn key ->
  if File.exists?(shared_env) do
    shared_env
    |> File.read!()
    |> String.split(~r/\R/, trim: true)
    |> Enum.find_value(fn line ->
      case String.split(line, "=", parts: 2) do
        [^key, value] -> value
        _ -> nil
      end
    end)
  end
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :auth_bantculture_com, AuthBantcultureComWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Mv4UHT3mB0Nxof+VHgD8OIGUXs//o0WoHscE6OJ0DOxDvovPsfr2pG9QHWdXjZD3",
  watchers: []

config :auth_bantculture_com, AuthBantcultureCom.Repo,
  url:
    System.get_env("AUTH_DATABASE_URL") ||
      System.get_env("DATABASE_URL") ||
      read_shared_env.("DATABASE_URL") ||
      raise("AUTH_DATABASE_URL or DATABASE_URL is missing"),
  show_sensitive_data_on_connection_error: true,
  pool_size: 5

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :auth_bantculture_com, AuthBantcultureComWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/auth_bantculture_com_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :auth_bantculture_com, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
